### PR TITLE
Update System.Web.(Helpers, Mvc, Razor, WebPages), Moq, Nunit, Reflectio...

### PR DESCRIPTION
**Pull request by jbgriffith**
Updated a bunch of NuGet packages

### CODE REVIEW

**Comment by jbgriffith** [comment]
@somedave, I am now having some issues with building the precompiled views. I keep getting the following error.
I have looked far and wide to find a solution, but I have come up empty handed, hopefully you can help shed some light?

Error	9
Could not precompile the file '\Views\Home\Index.cshtml'. Ensure that a generator declaration exists in the cshtml file. 
A generator declaration is the first line of your cshtml file and looks like this: 
@* Generator: MvcHelper *@
Valid host names: MvcHelper, MvcView, Template, WebPagesHelper, WebPage, RazorGenerator.Core.IHostProvider	C:\Users\jgriffith\Documents\Git Repositories\FluentBootstrap\packages\RazorGenerator.MsBuild.2.3.0\build\RazorGenerator.MsBuild.targets	Line:21	FluentBootstrap.Tests.Web

**Comment by somedave** [comment]
First - sorry I haven't looked at this PR yet. Hopefully I'll get to it soon. RazorGenerator can get goofy because of the way it precompiles the views and then caches the results. I suspect something has been locally cached and it's getting confused. I've found that sometimes I need to totally clean the project and rebuild. If that doesn't work, I'll manually delete the bin and obj folders and try again. Usually that clears it up. I know I've seen this exact error before (I use RazorGenerator pretty heavily for my blog, etc.) - I just don't remember offhand exactly what steps to take to clear it. Let me know if you get it compiling again, otherwise I can take a closer look this week.

**Comment by jbgriffith** [comment]
@somedave, No problem. I have noticed some goofiness with it also. 
I ran a clean on the solution, then deleted the bin and obj folders in all of the projects.
Rebuilt it and same error.
When you find the solution maybe create a script and/or tell RazorGenerator (@davidebbo) about it

**Comment by somedave** [comment]
Thought of one more thing to check - see if the tests project file has changed. You might need to re-run Enable-RazorGenerator to configure all the views (especially if you've updated package versions). Might also need to run Redo-RazorGenerator. Could also try resetting the build properties for the view to use RazorGenerator. See here near the bottom of the page: https://razorgenerator.codeplex.com Let me know if any of these steps work.

**Comment by jbgriffith** [comment]
@somedave, I ran Enable-RazorGenerator & Redo-RazorGenerator and it created the *.generated.cs files under each view file, then I got two errors for each file, that the ctor was a duplicate & execute was a duplicate. I then deleted the *.generated.cs files under each view and it build fine without issues and passed all tests. Seems to me we maybe didn't need Enable-RazorGenerator. I can try again, and see what happens.

**Comment by somedave** [comment]
Great - glad you got it working!

**Comment by jbgriffith** [comment]
@somedave well I had it working...
There has to be something I or we are missing, the results I am getting are not consistent at all..

**Comment by somedave** [comment]
I've merged the PR, thanks for another one!

I'm not totally happy with the versioning of dependencies though (and wasn't before your change - has nothing to do with your update). Really should be using a NuGet version range instead of a specific version. For example, users shouldn't need to update their MVC to 5.2 just because they bring in FluentBootstrap. Going to take a look at this problem now...

**Comment by jbgriffith** [comment]
So whats the trick with RazorGenerator to get it working its a Huge PITA? (IMHO)

**Pull request merged**
